<?php
/**
 * Placeholder插件配置文件
 */
return [
	[
		'name' => 'default_bgcolor',
		'title' => '默认背景色',
		'type' => 'string',
		'group' => '基础设置',
		'content' => '',
		'value' => '#CCCCCC',
		'rule' => 'required',
		'msg' => '',
		'tip' => '设置图片默认的背景颜色',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'default_textcolor',
		'title' => '默认文字色',
		'type' => 'string',
		'group' => '基础设置',
		'content' => '',
		'value' => '#969696',
		'rule' => 'required',
		'msg' => '',
		'tip' => '设置图片默认的文字颜色',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'default_format',
		'title' => '默认格式',
		'type' => 'select',
		'group' => '基础设置',
		'content' => [
			'png' => 'PNG',
			'jpg' => 'JPG',
			'jpeg' => 'JPEG',
			'gif' => 'GIF',
		],
		'value' => 'png',
		'rule' => 'required',
		'msg' => '',
		'tip' => '设置默认的图片格式',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'allow_formats',
		'title' => '允许的格式',
		'type' => 'checkbox',
		'group' => '基础设置',
		'content' => [
			'png' => 'PNG',
			'jpg' => 'JPG',
			'jpeg' => 'JPEG',
			'gif' => 'GIF',
			'bmp' => 'BMP',
		],
		'value' => 'png,jpg,gif,jpeg,bmp',
		'rule' => 'required',
		'msg' => '',
		'tip' => '设置允许使用的图片格式，多个格式用逗号分隔',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'font_file',
		'title' => '字体',
		'type' => 'ttf',
		'group' => '基础设置',
		'content' => '',
		'value' => '',
		'rule' => '',
		'msg' => '',
		'tip' => '设置文字字体',
		'ok' => '',
		'extend' => '',
	],
    [
		'name' => 'max_width',
		'title' => '最大宽度',
		'type' => 'number',
		'group' => '基础设置',
		'content' => '',
		'value' => 2000,
		'rule' => 'required|integer|min:100|max:5000',
		'msg' => '',
		'tip' => '设置生成图片的最大宽度限制（px）',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'max_height',
		'title' => '最大高度',
		'type' => 'number',
		'group' => '基础设置',
		'content' => '',
		'value' => 2000,
		'rule' => 'required|integer|min:100|max:5000',
		'msg' => '',
		'tip' => '设置生成图片的最大高度限制（px）',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'max_blur',
		'title' => '最大模糊度',
		'type' => 'number',
		'group' => '功能设置',
		'content' => '',
		'value' => 100,
		'rule' => 'required|integer|min:0|max:100',
		'msg' => '',
		'tip' => '设置模糊效果的最大模糊度',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'batch_maxcount',
		'title' => '批量生成限制',
		'type' => 'number',
		'group' => '功能设置',
		'content' => '',
		'value' => 20,
		'rule' => 'required|integer|min:1',
		'msg' => '',
		'tip' => '设置每次批量生成数量限制',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'remote_allow',
		'title' => '远程图片作为背景',
		'type' => 'switch',
		'group' => '功能设置',
		'content' => '',
		'value' => 1,
		'rule' => '',
		'msg' => '',
		'tip' => '是否允许远程图片作为背景',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'remote_timeout',
		'title' => '加载远程图片超时时间',
		'type' => 'number',
		'group' => '功能设置',
        'visible'  => 'remote_allow=1',
		'content' => '',
		'value' => 5,
		'rule' => '',
		'msg' => '',
		'tip' => '秒',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'history_enable',
		'title' => '保存历史记录',
		'type' => 'switch',
		'group' => '功能设置',
		'content' => '',
		'value' => 1,
		'rule' => '',
		'msg' => '',
		'tip' => '是否保存用户的历史生成记录',
		'ok' => '',
		'extend' => '',
	],
	[
		'name' => 'history_limit',
		'title' => '历史记录限制',
		'type' => 'number',
		'group' => '功能设置',
        'visible'  => 'history_enable=1',
		'content' => '',
		'value' => 12,
		'rule' => 'required|integer|min:1|max:50',
		'msg' => '',
		'tip' => '设置每个用户保存的历史记录数量限制',
		'ok' => '',
		'extend' => '',
	],
    [
        'name' => 'domain',
        'title' => '绑定二级域名前缀',
        'type' => 'string',
        'group' => '伪静态',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'group' => '伪静态',
        'content' => [],
        'value' => [
            'index/index' => '/placeholder/$',
            'index/image' => '/placeholder/image/[:size]/[:bgcolor]/[:textcolor]/[:text]',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];